[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "value_iteration"
version = "1.0.1"
maintainers = [
  { name="Harry Ellingham", email="h.ellingham@lancaster.ac.uk" },
]
authors = [
  { name="Harry Ellingham", email="h.ellingham@lancaster.ac.uk"},
]
description = "Implementation of value iteration for Markov Decision Processes"
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

dependencies = [
    "numpy>=2.2",
    "matplotlib>=3.10",
]

readme = { file = "pypi.md", content-type = "text/markdown" }

[project.optional-dependencies]
dev = ["pytest"]

[project.urls]
homepage = "https://github.com/Harry-Ell/601-assessment-2"

[tool.setuptools.packages.find]
where = ["."]