[project]
name = "my-tensor"
version = "0.1.0"
description = ""
authors = [
    {name = "vpakala_euc",email = "vpakala@omnissa.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy"
]

[tool.poetry]
packages = [{include = "my_tensor", from = "src"}]


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.5"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
