[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
testpaths = ["tests", "."]
python_files = "*_unit_test.py *_integration_test.py"

[tool.coverage.run]
source = ["."]
omit = ["setup.py", "tests/*", "*_unit_test.py", "*_integration_test.py", ".venv/*"]