[tool.poetry]
name = "kwark"
description = "Tap into AI brilliance from a simple shell command"
authors = ["Steampunk Wizard <kwark@steamwiz.io>"]
license = "MIT"
readme = "PACKAGE.md"
version = "1.0.0"

[tool.poetry.dependencies]
python = "~3.11"
wizlib = "3.3.1"
requests = "^2.32.3"
anthropic = "^0.45.2"

[tool.poetry.group.dev.dependencies]
pycodestyle = "^2.11.0"
autopep8 = "^2.0.4"
coverage = "^7.3.0"

[tool.poetry.scripts]
kwark = "kwark:KwarkApp.main"
