[project]
name = "mlops_wrapper"
version = "0.1.4"
description = "a unified mlflow wrapper for standardized ML model logging and registration."
readme = "README.md"
requires-python = ">=3.8"
license = { file = "LICENSE" }
authors = [
    { name = "akaay", email = "s.a.ashok91@gmail.com" }
]
dependencies = [
    "mlflow>=1.0.0",
    "boto3>=1.0.0"
]

[project.urls]
Homepage = "https://github.com/copernicium-112/mlops_wrapper"
Issues = "https://github.com/copernicium-112/mlops_wrapper/issues"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]