[project]
name = "scanpy-cli"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nictru", email = "nictru32@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "click>=8.1.8",
    "scanpy>=1.11.0",
]

[project.scripts]
scanpy-cli = "scanpy_cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.11.2",
]
