[project]
name = "mcp-server-oracle"
version = "1.0.0"
description = "Model Context Protocol server to access oracle database"
authors = [
    { name = "hdcola", email = "gh@hdcola.org" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.5.0",
    "oracledb>=3.0.0",
    "python-dotenv>=1.0.1",
]

[project.scripts]
mcp-server-oracle = "mcp_server_oracle:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
