[tool.ruff]
target-version = "py310"

[project]
name = "glootil"
version = "0.1.1"
description = "Library to build Gloodata extensions"
authors = [{ name = "Mariano Guerra", email = "mariano@gloodata.com" }]
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
]

[tool.pytest.ini_options]
pythonpath = ["./src/"]
