[tool.poetry]
name = "mh_logtools"
version = "0.1.2"
description = "Logging utility for machine health system"
authors = ["jtraa <joh.traa@gmail.com>"]
readme = "README.md"
packages = [{include = "mh_logtools"}]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
