[project]
name = "chatterer"
version = "0.1.11"
description = "The highest-level interface for various LLM APIs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["instructor>=1.7.2", "langchain>=0.3.19"]

[project.optional-dependencies]
dev = ["neo4j-extension>=0.1.14", "colorama>=0.4.6", "ipykernel>=6.29.5"]
conversion = [
    "markdownify>=1.1.0",
    "commonmark>=0.9.1",
    "playwright>=1.50.0",
    "pillow>=11.1.0",
    "mistune>=3.1.2",
    "markitdown>=0.0.2",
    "pymupdf>=1.25.4",
    "youtube-transcript-api>=1.0.2",
]
langchain = ["chatterer[langchain-providers]", "langchain-experimental>=0.3.4"]
langchain-providers = [
    "langchain-openai>=0.3.7",
    "langchain-anthropic>=0.3.8",
    "langchain-google-genai>=2.0.10",
    "langchain-ollama>=0.2.3",
]
all = ["chatterer[langchain]", "chatterer[conversion]", "chatterer[dev]"]
