[project]
name = "lrspline"
version = "1.15.1"
description = "Python bindings for the LRSplines library"
authors = [
    { name = "Eivind Fonn", email = "eivind.fonn@sintef.no" },
]
dependencies = [
    "numpy>=1.25,<3.0",
]
requires-python = ">=3.11,<4.0"
readme = "README.rst"

[project.license]
text = "GPL-3-or-later"

[build-system]
requires = [
    "pdm-backend",
    "setuptools>=66",
    "cython>=3",
    "numpy>=1.23",
]
build-backend = "pdm.backend"

[tool.pdm.build]
run-setuptools = true
source-includes = [
    "submodules/LRSplines/src/*.cpp",
    "submodules/LRSplines/include/**/*.h",
    "pdm_build.py",
]
excludes = [
    "tests",
]

[tool.mypy]
plugins = [
    "numpy.typing.mypy_plugin",
]
files = [
    "lrspline/**/*.py",
]
disallow_untyped_defs = true
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
warn_return_any = true
show_error_codes = true
mypy_path = "$MYPY_CONFIG_FILE_DIR/stubs"

[tool.ruff]
line-length = 110
include = [
    "lrspline/**/*.py",
    "lrspline/**/*.pyi",
    "tests/**/*.py",
]
exclude = [
    "tests/generated/**/*.py",
]

[tool.ruff.lint]
select = [
    "F",
    "W",
    "E",
    "I",
    "UP",
    "C4",
    "FA",
    "ISC",
    "ICN",
    "RET",
    "SIM",
    "TID",
    "TCH",
    "PTH",
    "TD",
    "NPY",
]
ignore = [
    "E741",
    "SIM115",
    "ISC001",
    "TD003",
]

[tool.ruff.lint.isort]
required-imports = [
    "from __future__ import annotations",
]

[tool.bumpversion]
allow_dirty = false
current_version = "1.15.1"
commit = true
tag = true
parse = "(?x)\n    (?P<major>[0-9]+)\n    \\.(?P<minor>[0-9]+)\n    \\.(?P<patch>[0-9]+)\n    (?:\n        (?P<pre_label>a|b|rc|stable)\n        (?P<pre_number>[0-9]+)?\n    )?\n"
serialize = [
    "{major}.{minor}.{patch}{pre_label}{pre_number}",
    "{major}.{minor}.{patch}",
]
message = "Bump version: {current_version} -> {new_version}"
tag_message = "Bump version: {current_version} -> {new_version}"
sign_tags = true
files = [
    { filename = "pyproject.toml" },
    { filename = "lrspline/__init__.py" },
]

[tool.bumpversion.parts.pre_label]
optional_value = "stable"
values = [
    "a",
    "b",
    "rc",
    "stable",
]

[tool.bumpversion.parts.pre_number]
first_value = "1"

[dependency-groups]
dev = [
    "bump-my-version>=0.17.4",
    "pytest>=8.0.1",
    "ruff>=0.2.2",
    "mypy>=1.8.0",
]
