[tool.poetry]
name = "aserto-directory"
version = "0.33.6"
description = "gRPC client for Aserto Directory service instances"
readme = "README.md"
authors = ["Aserto, Inc. <pypi@aserto.com>"]
homepage = "https://github.com/aserto-dev/python-directory"
repository = "https://github.com/aserto-dev/python-directory"
documentation = "https://github.com/aserto-dev/python-directory"
license = "Apache-2.0"
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: Apache Software License",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Software Development :: Libraries",
  "Typing :: Typed",
]
packages = [
    { include = "aserto", from = "src" },
    { include = "google", from = "src" },
    { include = "protoc_gen_openapiv2", from = "src" },
]


[tool.poetry.dependencies]
python = ">=3.9,<4"
grpcio = "^1.71.0"
protobuf = "^6.30.1"
types-protobuf = "^5.29"

[tool.poetry.group.dev.dependencies]
black = "^25.1.0"
isort = "^6.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
