[tool.poetry]
name = "dtpyutils"
version = "0.1.10"
description = "A package that has different utils, wrappers, and functions."
authors = ["Reza Shirazi <reza@datgate.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
python-jose = "^3.4.0"


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
