[project]
name = "material-color-utilities"
version = "0.2.3"
description = "Theme color library for Material You."
readme = "README.md"
license = { file = "LICENSE" }
authors = [
    { name = "Ruurd Bijlsma", email = "ruurd@bijlsma.dev" }
]
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.0",
    "pillow>=11.0.0",
]

[project.urls]
Homepage = "https://github.com/RuurdBijlsma/material-color-utilities"
Repository = "https://github.com/RuurdBijlsma/material-color-utilities"
Documentation = "https://github.com/RuurdBijlsma/material-color-utilities/blob/main/README.md"

[tool.ruff]
exclude = ['abseil-cpp']
lint.ignore = ["F811"]

[tool.scikit-build]
minimum-version = "build-system.requires"
build-dir = "build/{wheel_tag}"

[build-system]
requires = ["scikit-build-core>=0.10", "pybind11"]
build-backend = "scikit_build_core.build"

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "ruff>=0.8.4",
]
