[project]
name = "umnet-nornir-plugins"
version = "0.1.1"
description = "Nornir plugins for UMnet"
authors = [
    {name = "Amy Liebowitz",email = "amylieb@umich.edu"}
]
readme = "README.md"
requires-python = ">=3.10,<3.12"
dependencies = [
    "umnet-napalm (>=0.3.0,<0.4.0)"
]
[project.entry-points."nornir.plugins.connections"]
umnet_napalm = "umnet_nornir_plugins.connections:UMnetNapalm"

[project.entry-points."nornir.plugins.runners"]
multiprocess= "umnet_nornir_plugins.runners:MultiProcessRunner"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
