[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "office_tool_plus"
version = "0.1.0"
authors = [
    { name = "muzili", email = "1537080775@qq.com" },
]
description = "基于 Python 开发的自动化 office 工具包"
readme = "README.md"
requires-python = ">=3.6"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    'pywin32>=300; platform_system == "Windows"',
    "openpyxl>=3.0.0",
]
license = "MIT"
license-files = { paths = ["LICENSE"] }
[project.urls]
Gitee = "https://gitee.com/Muzi-Li-Chine/office_tool_plus"
Issues = "https://gitee.com/Muzi-Li-Chine/office_tool_plus/issues"