[tool.poetry]
name = "generic-consumer"
version = "0.20.0"
description = "A generic consumer for Python."
authors = ["Mister Nyan <michael.edmund.wong@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
simple-chalk = "*"
fun-things = "*"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
