[build-system]
requires = ["flit_core >=3.2, <3.11"] # THIS SHOULD BE REVERTED TO '["flit_core >=3.2,<4"]'
build-backend = "flit_core.buildapi"

[project]
# Check https://flit.readthedocs.io/en/latest/pyproject_toml.html for all available sections
name = "ansys-hps-data-transfer-client"
version = "0.2.0"
description = "Python client library for hps data transfer service"
readme = "README.rst"
requires-python = ">=3.10,<4.0"
license = {file = "LICENSE"}
authors = [
    {name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"},
]
maintainers = [
    {name = "ANSYS, Inc.", email = "pyansys.core@ansys.com"},
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "pydantic>=2.7.1",
    "httpx>=0.27.0,<0.28.0",
    "backoff>=2.2.1",
    "humanfriendly>=10.0",
    "requests>=2.21.0",
    "portend>=3.2.0",
    "filelock>=3.14.0",
    "psutil>=5.9.1",
    "asyncio-atexit>=1.0.0",
]

[project.optional-dependencies]
tests = [
    "pytest==8.3.5",
    "pytest-cov==6.0.0",
    "pytest-timeout==2.3.1",
    "pytest-mock-resources[redis]==2.12.2",
    "pytest-rerunfailures==15.0",
    "pytest-asyncio==0.25.3",
    "python-keycloak==5.3.1",
    "python-slugify>=8.0.4",
    "tox==4.24.2",
]
doc = [
    "ansys-sphinx-theme==1.2.6",
    "autodoc_pydantic==2.2.0",
    "jupyter_sphinx==0.5.3",
    "nbsphinx==0.9.6",
    "numpydoc==1.8.0",
    "myst-parser==4.0.0",
    "Sphinx==8.2.3",
    "sphinx-autoapi==3.6.0",
    "sphinx-autodoc-typehints==3.0.1",
    "sphinxcontrib-globalsubs==0.1.2",
    "sphinxcontrib-httpdomain==1.8.1",
    "sphinx-copybutton==0.5.2",
    "sphinx_design==0.6.1",
    "sphinx-jinja==2.0.2",
    "sphinxnotes-strike==1.2.1",
    "sphinx-tabs==3.4.7",
    "sphinx-gallery==0.19.0",
]

build = [
    "build==1.2.2.post1",
    "twine==6.1.0",
    "wheel",
    "datamodel-code-generator==0.26.3",
    "pre-commit==4.2.0",
    "importlib_metadata>=7.0",
]

[tool.flit.module]
name = "ansys.hps.data_transfer.client"

[project.urls]
Source = "https://github.com/ansys/pyhps-data-transfer/"
Tracker = "https://github.com/ansys/pyhps-data-transfer/issues"
Homepage = "https://github.com/ansys/pyhps-data-transfer/"
Documentation = "https://data-transfer.hps.docs.pyansys.com"

[tool.pydocstyle]
convention = "numpy"

[tool.pytest.ini_options]
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
addopts = "-ra -vv"
filterwarnings = [
    "ignore::urllib3.exceptions.InsecureRequestWarning",
    "ignore::DeprecationWarning:pkg_resources.*",
]

[tool.coverage.run]
relative_files = true
source = ["ansys.hps"]

[tool.coverage.report]
show_missing = true

[tool.coverage.html]
directory = ".cov/html"

[tool.coverage.xml]
output = ".cov/coverage.xml"

[tool.ruff]
line-length = 120
extend-exclude = ["examples/**/*.py"]

[tool.ruff.lint]
select = [
    "E",   # pycodestyle, see https://beta.ruff.rs/docs/rules/#pycodestyle-e-w
    "F",   # pyflakes, see https://beta.ruff.rs/docs/rules/#pyflakes-f
    "I",   # isort, see https://beta.ruff.rs/docs/rules/#isort-i
    "N",   # pep8-naming, see https://beta.ruff.rs/docs/rules/#pep8-naming-n
]
ignore = ["E402", "E712", "E722", "F401", "F841", "F821"]

[tool.ruff.lint.isort]
combine-as-imports = true
force-sort-within-sections = true
known-first-party = ["ansys"]

[tool.ruff.lint.pydocstyle]
# Settings: https://docs.astral.sh/ruff/settings/#lintpydocstyle
convention = "google"


[tool.towncrier]
package = "ansys.hps.data_transfer.client"
directory = "doc/changelog.d"
filename = "doc/source/changelog.rst"
start_string = ".. towncrier release notes start\n"
template = "doc/changelog.d/changelog_template.jinja"
title_format = "`{version} <https://github.com/ansys/ansys.hps.data_transfer_client/releases/tag/v{version}>`_ - {project_date}"
issue_format = "`#{issue} <https://github.com/ansys/ansys.hps.data_transfer_client/pull/{issue}>`_"

[[tool.towncrier.type]]
directory = "added"
name = "Added"
showcontent = true

[[tool.towncrier.type]]
directory = "changed"
name = "Changed"
showcontent = true

[[tool.towncrier.type]]
directory = "fixed"
name = "Fixed"
showcontent = true

[[tool.towncrier.type]]
directory = "dependencies"
name = "Dependencies"
showcontent = true

[[tool.towncrier.type]]
directory = "miscellaneous"
name = "Miscellaneous"
showcontent = true
