[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "calculationyash"
version = "0.1.0"
description = "A pakage which can reverse text"
readme = "README.md"
authors = [{ name = "Yash Sharma", email = "yash.innovater@gmail.com" }]
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = []
