[project]
name = "create-ragbits-app"
version = "0.0.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.13",
    "inquirer>=3.4.0",
    "jinja2>=3.1.6",
    "pydantic>=2.10.6",
    "rich>=13.9.4",
    "twine>=6.1.0",
]


[project.scripts]
create-ragbits-app = "create_ragbits_app.main:entrypoint"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/create_ragbits_app"]

[tool.hatch.build]
include = ['templates/**/*']