[project]
name = "iplooker"
version = "0.1.2"
description = "Look up location, ISP, and more about an IP address from multiple sources"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pycountry>=24.6.1",
    "requests>=2.32.3",
]

[tool.uv.sources]
dsbase = { workspace = true }

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
iplooker = "iplooker.main:main"
