[project]
name = "dsbase"
version = "0.4.0"
description = "Delightful Python utility library with power and personality"
authors = [{ name = "Danny Stewart", email = "danny@stewart.cc" }]
readme = "README.md"
urls = { repository = "https://github.com/dannystewart/dsbase" }
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "halo>=0.0.31,<0.0.32",
    "mysql-connector-python>=9.2.0,<10.0.0",
    "natsort>=8.4.0,<9.0.0",
    "packaging>=24.2,<25.0",
    "platformdirs>=4.3.7,<5.0.0",
    "pygments>=2.19.1,<3.0.0",
    "python-dateutil>=2.9.0.post0,<3.0.0",
    "python-dotenv>=1.0.1,<2.0.0",
    "pyyaml>=6.0.2,<7.0.0",
    "requests>=2.32.3,<3.0.0",
    "send2trash>=1.8.3,<2.0.0",
    "termcolor>=2.5.0,<3.0.0",
    "tomlkit>=0.13.2,<0.14.0",
    "types-requests>=2.32.0.20250306,<3.0.0.0",
    "types-send2trash>=1.8.2.7,<2.0.0.0",
    "tzdata>=2025.2",
    "tzlocal>=5.3.1",
    "watchdog>=6.0.0,<7.0.0",
]

[dependency-groups]
dev = [
    "mypy>=1.15.0",
    "pdoc>=15.0.1",
    "ruff>=0.11.2",
]

[tool.uv.workspace]
members = ["packages/*"]

[tool.hatch.metadata]
allow-direct-references = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
